---
name: Publish Python Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Generate merged schemas
        run: |
          cp src/cell_annotation_schema/schema/cell_annotation_schema.yaml build/general_schema.yaml
          gen-linkml src/cell_annotation_schema/schema/BICAN/BICAN_schema.yaml --output build/BICAN_schema.yaml --mergeimports --format yaml --no-materialize-attributes
          gen-linkml src/cell_annotation_schema/schema/CAP/CAP_schema.yaml --output build/CAP_schema.yaml --mergeimports --format yaml --no-materialize-attributes

      - name: Package release assets
        run: |
          mkdir -p src/cell_annotation_schema/schemas
          touch src/cas_schema/schemas/__init__.py
          cp build/general_schema.yaml src/cell_annotation_schema/schemas
          cp build/BICAN_schema.yaml src/cell_annotation_schema/schemas
          cp build/CAP_schema.yaml src/cell_annotation_schema/schemas

#      - name: Build source and wheel archives
#        run: poetry build
#
#      - name: Publish Package
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          repository-url: https://test.pypi.org/legacy/
#          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Publish distribution to PyPI
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --build -r testpypi -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

